[theme]
base="dark"  # Set default to dark mode
primaryColor="#00C851"  # A bright green for contrast
backgroundColor="#0E1117"  # Dark background
secondaryBackgroundColor="#262730"  # Darker panels (e.g., sidebar)
textColor="#FAFAFA"  # Almost white text
font="sans serif"
